package com.reuben.pastcare_spring.models;

import com.reuben.pastcare_spring.enums.InsightCategory;
import com.reuben.pastcare_spring.enums.InsightSeverity;
import com.reuben.pastcare_spring.enums.InsightType;
import jakarta.persistence.*;
import lombok.*;
import org.hibernate.annotations.Filter;

import java.time.Instant;

/**
 * Entity representing an AI-generated insight or recommendation.
 * Dashboard Phase 2.4: Advanced Analytics
 *
 * Insights are automatically generated by analyzing church data
 * to detect anomalies, trends, and provide recommendations.
 */
@Entity
@Table(name = "insights")
@Data
@Builder
@NoArgsConstructor
@AllArgsConstructor
@EqualsAndHashCode(callSuper = true)
@Filter(name = "churchFilter", condition = "church_id = :churchId")
public class Insight extends TenantBaseEntity {

    /**
     * Type of insight (ANOMALY, TREND, PREDICTION, etc.)
     */
    @Enumerated(EnumType.STRING)
    @Column(name = "insight_type", nullable = false, length = 50)
    private InsightType insightType;

    /**
     * Category of the insight (ATTENDANCE, GIVING, etc.)
     */
    @Enumerated(EnumType.STRING)
    @Column(name = "category", nullable = false, length = 50)
    private InsightCategory category;

    /**
     * Insight title/headline
     */
    @Column(name = "title", nullable = false, length = 200)
    private String title;

    /**
     * Detailed insight description
     */
    @Column(name = "description", nullable = false, columnDefinition = "TEXT")
    private String description;

    /**
     * Severity level of the insight
     */
    @Enumerated(EnumType.STRING)
    @Column(name = "severity", length = 20)
    @Builder.Default
    private InsightSeverity severity = InsightSeverity.INFO;

    /**
     * Whether this insight requires action
     */
    @Column(name = "actionable")
    @Builder.Default
    private Boolean actionable = false;

    /**
     * Optional URL to take action on the insight
     */
    @Column(name = "action_url", length = 500)
    private String actionUrl;

    /**
     * Whether the insight has been dismissed
     */
    @Column(name = "dismissed")
    @Builder.Default
    private Boolean dismissed = false;

    /**
     * When the insight was dismissed
     */
    @Column(name = "dismissed_at")
    private Instant dismissedAt;

    /**
     * User who dismissed the insight
     */
    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "dismissed_by")
    private User dismissedBy;

    /**
     * Additional metadata as JSON (data points, thresholds, etc.)
     */
    @Column(name = "metadata", columnDefinition = "JSON")
    private String metadata;

    /**
     * Check if insight is active (not dismissed)
     */
    public boolean isActive() {
        return !Boolean.TRUE.equals(dismissed);
    }

    /**
     * Dismiss this insight
     */
    public void dismiss(User user) {
        this.dismissed = true;
        this.dismissedAt = Instant.now();
        this.dismissedBy = user;
    }

    /**
     * Undismiss this insight
     */
    public void undismiss() {
        this.dismissed = false;
        this.dismissedAt = null;
        this.dismissedBy = null;
    }
}
