-- Phase 4: Lifecycle & Communication Tracking
-- Creates tables for lifecycle events, communication logs, and confidential notes

-- Create lifecycle_events table
CREATE TABLE lifecycle_events (
    id BIGINT AUTO_INCREMENT PRIMARY KEY,
    church_id BIGINT NOT NULL,
    member_id BIGINT NOT NULL,
    event_type VARCHAR(50) NOT NULL,
    event_date DATE NOT NULL,
    location VARCHAR(200),
    officiating_minister VARCHAR(100),
    certificate_number VARCHAR(100),
    notes TEXT,
    document_url VARCHAR(500),
    witnesses VARCHAR(500),
    is_verified BOOLEAN NOT NULL DEFAULT FALSE,
    verified_by_user_id BIGINT,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    FOREIGN KEY (church_id) REFERENCES church(id),
    FOREIGN KEY (member_id) REFERENCES member(id) ON DELETE CASCADE,
    FOREIGN KEY (verified_by_user_id) REFERENCES user(id) ON DELETE SET NULL,
    INDEX idx_lifecycle_events_member (member_id),
    INDEX idx_lifecycle_events_church (church_id),
    INDEX idx_lifecycle_events_type (event_type),
    INDEX idx_lifecycle_events_date (event_date),
    INDEX idx_lifecycle_events_verified (is_verified)
);

-- Create communication_logs table
CREATE TABLE communication_logs (
    id BIGINT AUTO_INCREMENT PRIMARY KEY,
    church_id BIGINT NOT NULL,
    member_id BIGINT NOT NULL,
    communication_type VARCHAR(50) NOT NULL,
    direction VARCHAR(20) NOT NULL,
    communication_date DATETIME NOT NULL,
    duration_minutes INT,
    subject VARCHAR(200) NOT NULL,
    notes TEXT,
    user_id BIGINT,
    follow_up_required BOOLEAN NOT NULL DEFAULT FALSE,
    follow_up_date DATETIME,
    follow_up_status VARCHAR(20),
    priority VARCHAR(20) DEFAULT 'NORMAL',
    outcome VARCHAR(500),
    is_confidential BOOLEAN NOT NULL DEFAULT FALSE,
    tags VARCHAR(500),
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    FOREIGN KEY (church_id) REFERENCES church(id),
    FOREIGN KEY (member_id) REFERENCES member(id) ON DELETE CASCADE,
    FOREIGN KEY (user_id) REFERENCES user(id) ON DELETE SET NULL,
    INDEX idx_communication_logs_member (member_id),
    INDEX idx_communication_logs_church (church_id),
    INDEX idx_communication_logs_type (communication_type),
    INDEX idx_communication_logs_date (communication_date),
    INDEX idx_communication_logs_follow_up (follow_up_required, follow_up_status),
    INDEX idx_communication_logs_priority (priority),
    INDEX idx_communication_logs_confidential (is_confidential)
);

-- Create confidential_notes table
CREATE TABLE confidential_notes (
    id BIGINT AUTO_INCREMENT PRIMARY KEY,
    church_id BIGINT NOT NULL,
    member_id BIGINT NOT NULL,
    category VARCHAR(50) NOT NULL,
    subject VARCHAR(200) NOT NULL,
    content TEXT NOT NULL,
    created_by_user_id BIGINT NOT NULL,
    last_modified_at DATETIME,
    last_modified_by_user_id BIGINT,
    priority VARCHAR(20) DEFAULT 'NORMAL',
    requires_follow_up BOOLEAN NOT NULL DEFAULT FALSE,
    follow_up_date DATETIME,
    follow_up_status VARCHAR(20),
    minimum_role_required VARCHAR(50),
    is_archived BOOLEAN NOT NULL DEFAULT FALSE,
    communication_log_id BIGINT,
    tags VARCHAR(500),
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    FOREIGN KEY (church_id) REFERENCES church(id),
    FOREIGN KEY (member_id) REFERENCES member(id) ON DELETE CASCADE,
    FOREIGN KEY (created_by_user_id) REFERENCES user(id),
    FOREIGN KEY (last_modified_by_user_id) REFERENCES user(id) ON DELETE SET NULL,
    FOREIGN KEY (communication_log_id) REFERENCES communication_logs(id) ON DELETE SET NULL,
    INDEX idx_confidential_notes_member (member_id),
    INDEX idx_confidential_notes_church (church_id),
    INDEX idx_confidential_notes_category (category),
    INDEX idx_confidential_notes_archived (is_archived),
    INDEX idx_confidential_notes_follow_up (requires_follow_up, follow_up_status),
    INDEX idx_confidential_notes_priority (priority)
);
