-- Create recurring_donations table
CREATE TABLE recurring_donations (
    id BIGINT AUTO_INCREMENT PRIMARY KEY,
    church_id BIGINT NOT NULL,
    member_id BIGINT NOT NULL,
    amount DECIMAL(10, 2) NOT NULL,
    donation_type VARCHAR(50) NOT NULL DEFAULT 'TITHE',
    frequency VARCHAR(20) NOT NULL,
    status VARCHAR(20) NOT NULL DEFAULT 'ACTIVE',
    start_date DATE NOT NULL,
    end_date DATE,
    next_charge_date DATE NOT NULL,
    last_charge_date DATETIME,
    currency VARCHAR(3) DEFAULT 'GHS',
    paystack_authorization_code VARCHAR(255),
    paystack_customer_code VARCHAR(100),
    paystack_plan_code VARCHAR(100),
    card_last4 VARCHAR(20),
    card_brand VARCHAR(50),
    card_bin VARCHAR(255),
    campaign VARCHAR(200),
    consecutive_failures INT NOT NULL DEFAULT 0,
    last_failure_date DATETIME,
    last_failure_reason TEXT,
    total_payments INT NOT NULL DEFAULT 0,
    total_amount_paid DECIMAL(10, 2) DEFAULT 0.00,
    notes TEXT,
    created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    FOREIGN KEY (church_id) REFERENCES churches(id) ON DELETE CASCADE,
    FOREIGN KEY (member_id) REFERENCES members(id) ON DELETE CASCADE,
    INDEX idx_recurring_member (member_id),
    INDEX idx_recurring_status (status),
    INDEX idx_recurring_next_charge (next_charge_date)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
