-- Create payment_transactions table
CREATE TABLE payment_transactions (
    id BIGINT AUTO_INCREMENT PRIMARY KEY,
    church_id BIGINT NOT NULL,
    member_id BIGINT NOT NULL,
    donation_id BIGINT,
    recurring_donation_id BIGINT,
    amount DECIMAL(10, 2) NOT NULL,
    currency VARCHAR(3) DEFAULT 'GHS',
    donation_type VARCHAR(50) NOT NULL,
    payment_method VARCHAR(50) NOT NULL,
    status VARCHAR(20) NOT NULL,
    payment_reference VARCHAR(255) UNIQUE,
    paystack_reference VARCHAR(255),
    paystack_transaction_id VARCHAR(100),
    paystack_authorization_code VARCHAR(255),
    card_last4 VARCHAR(20),
    card_brand VARCHAR(50),
    card_bin VARCHAR(255),
    gateway_response TEXT,
    gateway_message TEXT,
    paid_at DATETIME,
    failed_at DATETIME,
    retry_count INT NOT NULL DEFAULT 0,
    next_retry_at DATETIME,
    failure_reason TEXT,
    customer_email VARCHAR(255),
    customer_phone VARCHAR(50),
    campaign VARCHAR(200),
    notes TEXT,
    created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    FOREIGN KEY (church_id) REFERENCES churches(id) ON DELETE CASCADE,
    FOREIGN KEY (member_id) REFERENCES members(id) ON DELETE CASCADE,
    FOREIGN KEY (donation_id) REFERENCES donations(id) ON DELETE SET NULL,
    FOREIGN KEY (recurring_donation_id) REFERENCES recurring_donations(id) ON DELETE SET NULL,
    INDEX idx_payment_member (member_id),
    INDEX idx_payment_status (status),
    INDEX idx_payment_reference (payment_reference),
    INDEX idx_payment_recurring (recurring_donation_id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
