-- Seed data for test users
-- Users with different roles for each test church
-- Password for all test users: "Password@123"
-- BCrypt hash: $2a$10$YourBCryptHashHere (will be generated by PasswordEncoder in tests)

-- Alpha Test Church Users (Church ID: 1)
INSERT INTO users (id, name, email, phone_number, title, church_id, password, role, failed_login_attempts, account_locked, created_at, updated_at)
VALUES
    -- Admin user for Alpha Church
    (1, 'Alice Admin', 'alice.admin@alphatestchurch.com', '+254711000001', 'Church Administrator', 1, '$2a$10$rN8YlZpJx3z.xJqxF5qK5.GqU9K5lGqU9K5lGqU9K5lGqU9K5lGqU', 'ADMIN', 0, false, NOW(), NOW()),

    -- Pastor user for Alpha Church
    (2, 'Peter Pastor', 'peter.pastor@alphatestchurch.com', '+254711000002', 'Senior Pastor', 1, '$2a$10$rN8YlZpJx3z.xJqxF5qK5.GqU9K5lGqU9K5lGqU9K5lGqU9K5lGqU', 'PASTOR', 0, false, NOW(), NOW()),

    -- Treasurer user for Alpha Church
    (3, 'Tom Treasurer', 'tom.treasurer@alphatestchurch.com', '+254711000003', 'Church Treasurer', 1, '$2a$10$rN8YlZpJx3z.xJqxF5qK5.GqU9K5lGqU9K5lGqU9K5lGqU9K5lGqU', 'TREASURER', 0, false, NOW(), NOW()),

    -- Member Manager user for Alpha Church
    (4, 'Mary Manager', 'mary.manager@alphatestchurch.com', '+254711000004', 'Member Manager', 1, '$2a$10$rN8YlZpJx3z.xJqxF5qK5.GqU9K5lGqU9K5lGqU9K5lGqU9K5lGqU', 'MEMBER_MANAGER', 0, false, NOW(), NOW()),

    -- Fellowship Leader user for Alpha Church
    (5, 'Frank Leader', 'frank.leader@alphatestchurch.com', '+254711000005', 'Fellowship Leader', 1, '$2a$10$rN8YlZpJx3z.xJqxF5qK5.GqU9K5lGqU9K5lGqU9K5lGqU9K5lGqU', 'FELLOWSHIP_LEADER', 0, false, NOW(), NOW()),

    -- Regular Member user for Alpha Church
    (6, 'Mike Member', 'mike.member@alphatestchurch.com', '+254711000006', null, 1, '$2a$10$rN8YlZpJx3z.xJqxF5qK5.GqU9K5lGqU9K5lGqU9K5lGqU9K5lGqU', 'MEMBER', 0, false, NOW(), NOW());

-- Beta Test Church Users (Church ID: 2)
INSERT INTO users (id, name, email, phone_number, title, church_id, password, role, failed_login_attempts, account_locked, created_at, updated_at)
VALUES
    -- Admin user for Beta Church
    (7, 'Bob Admin', 'bob.admin@betatestchurch.com', '+254712000001', 'Church Administrator', 2, '$2a$10$rN8YlZpJx3z.xJqxF5qK5.GqU9K5lGqU9K5lGqU9K5lGqU9K5lGqU', 'ADMIN', 0, false, NOW(), NOW()),

    -- Pastor user for Beta Church
    (8, 'Paul Pastor', 'paul.pastor@betatestchurch.com', '+254712000002', 'Senior Pastor', 2, '$2a$10$rN8YlZpJx3z.xJqxF5qK5.GqU9K5lGqU9K5lGqU9K5lGqU9K5lGqU', 'PASTOR', 0, false, NOW(), NOW());

-- Gamma Test Church Users (Church ID: 3)
INSERT INTO users (id, name, email, phone_number, title, church_id, password, role, failed_login_attempts, account_locked, created_at, updated_at)
VALUES
    -- Admin user for Gamma Church
    (9, 'Charlie Admin', 'charlie.admin@gammatestchurch.com', '+254713000001', 'Church Administrator', 3, '$2a$10$rN8YlZpJx3z.xJqxF5qK5.GqU9K5lGqU9K5lGqU9K5lGqU9K5lGqU', 'ADMIN', 0, false, NOW(), NOW());

-- Superadmin User (No church association)
INSERT INTO users (id, name, email, phone_number, title, church_id, password, role, failed_login_attempts, account_locked, created_at, updated_at)
VALUES
    (10, 'Super Admin', 'superadmin@pastcare.com', '+254700000000', 'Platform Administrator', null, '$2a$10$rN8YlZpJx3z.xJqxF5qK5.GqU9K5lGqU9K5lGqU9K5lGqU9K5lGqU', 'SUPERADMIN', 0, false, NOW(), NOW());

-- Note: The password hashes above are placeholders
-- In actual tests, use PasswordEncoder to generate real BCrypt hashes
-- Or use the BaseIntegrationTest helper methods which handle password encoding
